spring:
  application:
    name: spring-boot-redis

  redis:
    database: 10 #Redis数据库索引（redis 桶，16个通）
    host: 192.168.10.196 # Redis服务器地址
    port: 30684 # Redis服务器连接端口
    password: yLIq9R5IGk # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-idle: 500 # 最大空闲连接数
        min-idle: 50 # 最小空闲连接数
        max-wait: 2000 # 等待可用连接的最大时间，负数为不限制
        max-active: 50  # 最大活跃连接数，负数为不限制
    timeout: 10000 # 连接超时时间 毫秒（默认2000）