spring:
  datasource:
    primary:
      password: tnbLMo2jXn
      jdbc-url: jdbc:mysql://192.168.10.196:30156/top.ipzgo.spring.ioc.lookup.test?characterEncoding=utf8&useSSL=true
      username: root
    secondary:
      password: tnbLMo2jXn
      jdbc-url: jdbc:mysql://192.168.10.196:30156/test2?characterEncoding=utf8&useSSL=true
      username: root
  application:
    name: multi-datasource
server:
  port: 8080