spring:
  application:
    name: multi-rabbitmq
  rabbitmq:
    first:
      host: 192.168.10.196
      port: 31443
      username: user
      password: OMHmqG9b95
    second:
      host: 192.168.10.196
      port: 32260
      username: user
      password: 5f3leONVte