spring:
  application:
    name: multi-rabbitmq
  rabbitmq:
    first:
      host: 192.168.10.76
      port: 30509
      username: admin
      password: wowjoy
    second:
      host: 192.168.10.76
      port: 31938
      username: admin
      password: wowjoy